//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model.Refactored
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankaccounttype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bankaccounttype()
        {
            this.bankaccountdetails = new HashSet<bankaccountdetail>();
        }
    
        public int bankAccountTypeID { get; set; }
        public string bankAccountTypeCode { get; set; }
        public string bankAccountTypeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bankaccountdetail> bankaccountdetails { get; set; }
    }
}
