//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model.Refactored
{
    using System;
    using System.Collections.Generic;
    
    public partial class custodian
    {
        public int custodianID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string jobTitle { get; set; }
        public string companyNumber { get; set; }
        public string email { get; set; }
        public string landline { get; set; }
        public string cell { get; set; }
        public Nullable<int> organizationID { get; set; }
    }
}
