//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model.Refactored
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizationmapping
    {
        public int organizationMappingID { get; set; }
        public Nullable<int> organizationID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
