//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model.Refactored
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int ratingID { get; set; }
        public string ownerType { get; set; }
        public string owningID { get; set; }
        public Nullable<int> rating1 { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
