//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model.Refactored
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rfq()
        {
            this.quotestatus = new HashSet<quotestatu>();
        }
    
        public int rfqID { get; set; }
        public string reference { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> expertiseSubCategoryID { get; set; }
        public string rfqDetails { get; set; }
        public Nullable<int> rfqTypeID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string status { get; set; }
    
        public virtual expertisesubcategory expertisesubcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quotestatu> quotestatus { get; set; }
        public virtual rfqtype rfqtype { get; set; }
        public virtual user user { get; set; }
    }
}
