//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model.Refactored
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.rfqs = new HashSet<rfq>();
        }
    
        public int userID { get; set; }
        public Nullable<int> organizationID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string passwordSalt { get; set; }
        public string title { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string identificationNumber { get; set; }
        public bool isApproved { get; set; }
        public string isLockedOut { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
        public Nullable<System.DateTime> lastPasswordChange { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<int> failedPasswordAttemptCount { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string employeeCode { get; set; }
        public string departmentCode { get; set; }
        public string useruuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfq> rfqs { get; set; }
    }
}
