//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class addresstype
    {
        public addresstype()
        {
            this.addresses = new HashSet<address>();
        }
    
        public int addressTypeID { get; set; }
        public string addressTypeTLA { get; set; }
        public string AddressTypeDescription { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
    }
}
