//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public long addressID { get; set; }
        public string owningType { get; set; }
        public string owningID { get; set; }
        public Nullable<int> addressTypeID { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string addressLine3 { get; set; }
        public string addressLine4 { get; set; }
        public string addressLine5 { get; set; }
        public string postalCode { get; set; }
    
        public virtual addresstype addresstype { get; set; }
    }
}
