//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankaccounttype
    {
        public bankaccounttype()
        {
            this.bankaccountdetails = new HashSet<bankaccountdetail>();
        }
    
        public int bankAccountTypeID { get; set; }
        public string bankAccountTypeCode { get; set; }
        public string bankAccountTypeDescription { get; set; }
    
        public virtual ICollection<bankaccountdetail> bankaccountdetails { get; set; }
    }
}
