//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankaccountdetail
    {
        public long bankAccountDetailID { get; set; }
        public string owningType { get; set; }
        public string owningID { get; set; }
        public string accountName { get; set; }
        public string accountNumber { get; set; }
        public string branchCode { get; set; }
        public string branchName { get; set; }
        public Nullable<bool> @default { get; set; }
        public Nullable<int> bankAccountTypeID { get; set; }
        public string bankName { get; set; }
    
        public virtual bankaccounttype bankaccounttype { get; set; }
    }
}
