//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class communication
    {
        public long communicationID { get; set; }
        public string owningType { get; set; }
        public string owningID { get; set; }
        public string communicationLine1 { get; set; }
        public string communicationLine2 { get; set; }
        public Nullable<int> communicationTypeID { get; set; }
        public string role { get; set; }
    
        public virtual communicationtype communicationtype { get; set; }
    }
}
