//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class documenttype
    {
        public documenttype()
        {
            this.documentrequirements = new HashSet<documentrequirement>();
            this.documents = new HashSet<document>();
        }
    
        public int documentTypeID { get; set; }
        public string documentCode { get; set; }
        public string documentDescription { get; set; }
    
        public virtual ICollection<documentrequirement> documentrequirements { get; set; }
        public virtual ICollection<document> documents { get; set; }
    }
}
