//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class expertisecategory
    {
        public expertisecategory()
        {
            this.expertisesubcategories = new HashSet<expertisesubcategory>();
        }
    
        public int ExpertiseCategoryID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<expertisesubcategory> expertisesubcategories { get; set; }
    }
}
