//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class expertiseownership
    {
        public int expertiseOwnershipID { get; set; }
        public string ownerType { get; set; }
        public string owningID { get; set; }
        public Nullable<int> expertiseSubCategoryID { get; set; }
    
        public virtual expertisesubcategory expertisesubcategory { get; set; }
    }
}
