//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizationweighting
    {
        public long organizationWeightingID { get; set; }
        public Nullable<decimal> weighting { get; set; }
        public Nullable<int> organizationID { get; set; }
        public Nullable<decimal> organizationInfo { get; set; }
        public Nullable<decimal> financeInfo { get; set; }
        public Nullable<decimal> hrInfo { get; set; }
        public Nullable<decimal> beeInfo { get; set; }
        public Nullable<decimal> insuranceInfo { get; set; }
        public Nullable<decimal> iso9001 { get; set; }
        public Nullable<decimal> iso40001 { get; set; }
        public Nullable<decimal> iso18001 { get; set; }
        public Nullable<decimal> totalWeighting { get; set; }
    }
}
