//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfq
    {
        public int rfqID { get; set; }
        public string reference { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> expertiseSubCategoryID { get; set; }
        public string rfqDetails { get; set; }
        public Nullable<int> rfqTypeID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string status { get; set; }
    
        public virtual expertisesubcategory expertisesubcategory { get; set; }
        public virtual rfqtype rfqtype { get; set; }
        public virtual user user { get; set; }
    }
}
