//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfqtype
    {
        public rfqtype()
        {
            this.rfqs = new HashSet<rfq>();
        }
    
        public int rfqTypeID { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string Prefix { get; set; }
    
        public virtual ICollection<rfq> rfqs { get; set; }
    }
}
