//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBoard.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TBoardEntities : DbContext
    {
        public TBoardEntities()
            : base("name=TBoardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<addresstype> addresstypes { get; set; }
        public DbSet<bankaccountdetail> bankaccountdetails { get; set; }
        public DbSet<bankaccounttype> bankaccounttypes { get; set; }
        public DbSet<communication> communications { get; set; }
        public DbSet<communicationtype> communicationtypes { get; set; }
        public DbSet<organization> organizations { get; set; }
        public DbSet<organizationtype> organizationtypes { get; set; }
    }
}
